services:
  # バックエンド（Django API）
  - type: web
    name: running-analysis-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-minimal.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --run-syncdb
    startCommand: |
      gunicorn running_analysis_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: running_analysis_project.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
    healthCheckPath: /api/health/
    
  # フロントエンド（React）
  - type: web
    name: running-analysis-frontend
    env: node
    plan: free
    buildCommand: |
      ls -la frontend/public/
      cd frontend
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd frontend && npx serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: REACT_APP_API_URL
        value: https://running-analysis-api.onrender.com 